language: R
pandoc_version: 1.17.2
cache:
  packages: true

addons:
  apt:
    packages:
      - libxml2-dev

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
